### ISSUE TITLE
Home Weather Station -- Runtime Error

### ISSUE THREAD

**Issue by jonathanrjpereira** [DexterInd/GrovePi#478]
**Installation Steps:**
```
git clone https://github.com/DexterInd/GrovePi
curl -kL dexterindustries.com/update_grovepi | bash
```

**Error:**
```
Python 3.7.3 (/usr/bin/python3)
>>> %cd /home/pi/Dexter/GrovePi/Projects/Home_Weather_Display
>>> %Run Home_Weather_Display.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/smbus_cffi-0.5.1-py3.7-linux-armv7l.egg/smbus/smbus.py", line 81, in open
    self._fd = os.open(path, os.O_RDWR, 0)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Dexter/GrovePi/Projects/Home_Weather_Display/Home_Weather_Display.py", line 41, in <module>
    from grove_rgb_lcd import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/grovepi-1.0.4-py3.7.egg/grove_rgb_lcd.py", line 33, in <module>
    bus = smbus.SMBus(1)
  File "/usr/local/lib/python3.7/dist-packages/smbus_cffi-0.5.1-py3.7-linux-armv7l.egg/smbus/smbus.py", line 56, in __init__
    self.open(bus)
  File "/usr/local/lib/python3.7/dist-packages/smbus_cffi-0.5.1-py3.7-linux-armv7l.egg/smbus/smbus.py", line 83, in open
    raise IOError(e.errno)
OSError: 2
```

**Raspberry Pi Specs:**
Raspberry Pi 3B+
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

**Comment by DAnGioi** [comment]
You can try this: curl -kL dexterindustries.com/update_grovepi | bash -s -- --user-local

**Comment by DAnGioi** [comment]
Help me！My GrovePi’s RST often light up after hours of work .My GrovePi’s RST often light up after hours of work.

**Comment by DAnGioi** [comment]
Are you having the same problem?My GrovePi’s RST often light up after hours of work

**Comment by jonathanrjpereira** [comment]
I'm not having problems with any of the GrovePi lights.

**Comment by CleoQc** [comment]
@jonathanrjpereira 
what do you get if you run `sudo i2cdetect -y 1` ?
It seems i2c isn't enabled.

**Comment by CleoQc** [comment]
Closing since no answer
