### ISSUE TITLE
Ruby test code doesn't run, i2c-devices library problem?

### ISSUE THREAD

**Issue by iandouglas** [DexterInd/GrovePi#497]
I installed the repo tonight, flashed the firmware, all of it said it was successful.

I updated the script to use D2 since I already had a grove temperature sensor plugged in there, but I'm getting this error:

```bash
~/Dexter/GrovePi/Software/Ruby/tests $ ruby test_read_digital.rb
Traceback (most recent call last):
	11: from test_read_digital.rb:3:in `<main>'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /home/pi/Dexter/GrovePi/Software/Ruby/grove_pi.rb:3:in `<top (required)>'
	 7: from /home/pi/Dexter/GrovePi/Software/Ruby/grove_pi.rb:5:in `<module:GrovePi>'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	 3: from /var/lib/gems/2.5.0/gems/i2c-devices-0.0.6/lib/i2c/driver/i2c-dev.rb:3:in `<top (required)>'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/i2c-devices-0.0.6/lib/i2c/driver.rb:5:in `<top (required)>': uninitialized constant I2CDevice (NameError)
```

**Comment by CleoQc** [comment]
We're sorry. Ruby was given to us by the community. 
We don't have anyone on staff that would be Ruby knowledgeable. 

We'll have to trust the community for this one.
